//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public int Id { get; set; }
        public string LigneAdresse { get; set; }
        public string CodePostal { get; set; }
    
        public virtual Pays Pays { get; set; }
    }
}
