//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresseLocale : Adresse
    {
        public string Daira { get; set; }
        public string Commune { get; set; }
    
        public virtual Wilaya Wilaya { get; set; }
    }
}
