//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteBancaire
    {
        public int Id { get; set; }
        public string NumCompte { get; set; }
    
        public virtual Entreprise Entreprise { get; set; }
        public virtual Banque Banque { get; set; }
    }
}
