//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conteneur
    {
        public string Id { get; set; }
        public string Ref { get; set; }
        public Nullable<decimal> Poids { get; set; }
    
        public virtual Connaissement Connaissement { get; set; }
        public virtual TypeConteneur Type { get; set; }
    }
}
