//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entreprise()
        {
            this.Motifs = new HashSet<MotifFacture>();
            this.ComptesBancaires = new HashSet<CompteBancaire>();
        }
    
        public int Id { get; set; }
        public string RegistreCommerce { get; set; }
        public string Denomination { get; set; }
        public string DenominationAR { get; set; }
        public Nullable<double> Capital { get; set; }
        public string NumArticle { get; set; }
        public string NIF { get; set; }
        public string NIS { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string SiteWeb { get; set; }
    
        public virtual Adresse Adresse1 { get; set; }
        public virtual Adresse Adresse2 { get; set; }
        public virtual Fichier Logo { get; set; }
        public virtual TypeEntreprise Type { get; set; }
        public virtual StatutJuridique StatutJuridique { get; set; }
        public virtual Personne Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotifFacture> Motifs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompteBancaire> ComptesBancaires { get; set; }
        public virtual Personne Gerant { get; set; }
        public virtual TypeActivite TypeActivite { get; set; }
    }
}
