//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactureFrais : Facture
    {
        public Nullable<double> Montant { get; set; }
        public string Remarque { get; set; }
    
        public virtual MotifFacture Motif { get; set; }
        public virtual Entreprise Beneficiaire { get; set; }
    }
}
