//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactureProforma : FactureFournisseur
    {
        public Nullable<System.DateTime> DateEmbarquement { get; set; }
        public Nullable<System.DateTime> DateDebarquement { get; set; }
        public string NPredomiciliation { get; set; }
        public Nullable<System.DateTime> DatePredomiciliation { get; set; }
    
        public virtual Importation Importation { get; set; }
        public virtual Port PortEmbarquement { get; set; }
        public virtual Port PortDebarquement { get; set; }
        public virtual ModeReglement ModeReglement { get; set; }
        public virtual Devise Devise { get; set; }
        public virtual Incoterm Incoterm { get; set; }
    }
}
