//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Importation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Importation()
        {
            this.FraisDivers = new HashSet<FactureFrais>();
            this.Offres = new HashSet<Offre>();
            this.Financements = new HashSet<Financement>();
            this.Arrivage = new HashSet<LigneCommande>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateDebarquement { get; set; }
        public Nullable<System.DateTime> DateNegociation { get; set; }
        public Nullable<System.DateTime> DateDomiciliation { get; set; }
        public Nullable<System.DateTime> DateDedouanement { get; set; }
        public Nullable<System.DateTime> DateCloturation { get; set; }
        public Nullable<System.DateTime> DateArrivee { get; set; }
        public Nullable<double> CoursDomiciliation { get; set; }
        public Nullable<double> CoursDedouanement { get; set; }
        public Nullable<double> CoursAchat { get; set; }
    
        public virtual Importateur Importateur { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual FactureProforma FactureProforma { get; set; }
        public virtual FactureDefinitive FactureDefinitive { get; set; }
        public virtual TaxeDouanier D10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactureFrais> FraisDivers { get; set; }
        public virtual AgenceBanque BanqueImportateur { get; set; }
        public virtual AgenceBanque BanqueFournisseur { get; set; }
        public virtual Activite Activite { get; set; }
        public virtual FactureTransit FactureTransit { get; set; }
        public virtual Commande Commande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offre> Offres { get; set; }
        public virtual Pays PaysOrigine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financement> Financements { get; set; }
        public virtual DestinationProduit DestinationProduit { get; set; }
        public virtual RecetteImpots RecetteImpots { get; set; }
        public virtual Transit Transit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneCommande> Arrivage { get; set; }
        public virtual Document Connaissement { get; set; }
        public virtual Document CertificatDeConformite { get; set; }
        public virtual Document CertificatDOrigine { get; set; }
        public virtual Document ListeDeColissage { get; set; }
    }
}
