//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Importation> Importations { get; set; }
        public virtual DbSet<Entreprise> Entreprises { get; set; }
        public virtual DbSet<Facture> Factures { get; set; }
        public virtual DbSet<LigneFacture> LigneFactures { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<AgenceBanque> AgenceBanques { get; set; }
        public virtual DbSet<Catalogue> Catalogues { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Chapitre> Chapitres { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<SousPosition> SousPositions { get; set; }
        public virtual DbSet<Adresse> Adresses { get; set; }
        public virtual DbSet<Wilaya> Wilayas { get; set; }
        public virtual DbSet<TaxeDouanier> TaxeDouaniers { get; set; }
        public virtual DbSet<Connaissement> Connaissements { get; set; }
        public virtual DbSet<Fichier> Fichiers { get; set; }
        public virtual DbSet<Conteneur> Conteneurs { get; set; }
        public virtual DbSet<ReferenceFournisseur> ReferenceFournisseurs { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
        public virtual DbSet<TypeConteneur> TypesConteneurs { get; set; }
        public virtual DbSet<ModeReglement> ModesReglement { get; set; }
        public virtual DbSet<TypeEntreprise> TypesEntreprises { get; set; }
        public virtual DbSet<StatutJuridique> StatutsJuridiques { get; set; }
        public virtual DbSet<Devise> Devises { get; set; }
        public virtual DbSet<MotifFacture> MotifFactures { get; set; }
        public virtual DbSet<UQN> UQNs { get; set; }
        public virtual DbSet<Activite> Activites { get; set; }
        public virtual DbSet<Produit> Produits { get; set; }
        public virtual DbSet<Attribut> Attributs { get; set; }
        public virtual DbSet<Valeur> Valeurs { get; set; }
        public virtual DbSet<LigneCommande> LigneCommandes { get; set; }
        public virtual DbSet<Paiement> Paiements { get; set; }
        public virtual DbSet<Echeance> Echeances { get; set; }
        public virtual DbSet<TypeEcheance> TypeEcheances { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Financement> Financements { get; set; }
        public virtual DbSet<DestinationProduit> DestinationProduits { get; set; }
        public virtual DbSet<RecetteImpots> RecetteImpots { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<CompteBancaire> ComptesBancaires { get; set; }
        public virtual DbSet<TypeActivite> TypesActivites { get; set; }
        public virtual DbSet<Incoterm> Incoterms { get; set; }
        public virtual DbSet<Packaging> Packagings { get; set; }
    }
}
