//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<Titre> Titre { get; set; }
        public string Fonction { get; set; }
        public string Tel { get; set; }
        public string EMail { get; set; }
        public string NIS { get; set; }
        public string NIF { get; set; }
    
        public virtual Entreprise Entreprise { get; set; }
        public virtual Adresse Adresse { get; set; }
    }
}
