//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SousPosition
    {
        public string Code { get; set; }
        public string Designation { get; set; }
        public string GU { get; set; }
        public Nullable<double> TVA { get; set; }
        public Nullable<double> DD { get; set; }
        public string Cle { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual UQN UQN { get; set; }
    }
}
