//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valeur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Valeur()
        {
            this.Fils = new HashSet<Valeur>();
        }
    
        public int Id { get; set; }
        public string ValeurFR { get; set; }
        public string ValeurAR { get; set; }
        public string ValeurEN { get; set; }
    
        public virtual Attribut Attribut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valeur> Fils { get; set; }
        public virtual Valeur Pere { get; set; }
    }
}
