//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.Importations
{
    using System; 
    using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
    internal class Importations { }
#else

    public class Importations : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public Importations()
        {
            try
            {
                Uri resourceUri = new Uri("/ImportManager;component/SampleData/Importations/Importations.xaml", UriKind.RelativeOrAbsolute);
                System.Windows.Application.LoadComponent(this, resourceUri);
            }
            catch
            {
            }
        }

        private ImportationsList _ImportationsList = new ImportationsList();

        public ImportationsList ImportationsList
        {
            get
            {
                return this._ImportationsList;
            }
        }
    }

    public class ImportationsListItem : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private double _NumImport = 0;

        public double NumImport
        {
            get
            {
                return this._NumImport;
            }

            set
            {
                if (this._NumImport != value)
                {
                    this._NumImport = value;
                    this.OnPropertyChanged("NumImport");
                }
            }
        }

        private string _DateCreation = string.Empty;

        public string DateCreation
        {
            get
            {
                return this._DateCreation;
            }

            set
            {
                if (this._DateCreation != value)
                {
                    this._DateCreation = value;
                    this.OnPropertyChanged("DateCreation");
                }
            }
        }

        private string _Fournisseur = string.Empty;

        public string Fournisseur
        {
            get
            {
                return this._Fournisseur;
            }

            set
            {
                if (this._Fournisseur != value)
                {
                    this._Fournisseur = value;
                    this.OnPropertyChanged("Fournisseur");
                }
            }
        }
    }

    public class ImportationsList : System.Collections.ObjectModel.ObservableCollection<ImportationsListItem>
    { 
    }
#endif
}
